### PR TITLE
Integration/react js

### PR DESCRIPTION
**Pull request by TheLuisAbarca**
1. Create a new Rails app called 'hello-rails-react'.
2. Initialize your project with Git.
3. Set up your project with webpacker the react-rails gems as describe in the previous lesson's tutorial.
4. Make sure that your project has a Postgres database set up.
5. Create a table for storing your messages and create 5 different greetings.
6. Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
7. Create a static view that will be the root of your app.
8. Create the App component with react-router and render it in your static view.
9. Create the Greeting component that will display a greeting. Set it up as a route in your App component.
10. Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
11. Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by TheLuisAbarca** [comment]
Im getting an error with stylelint:

Run npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-05-04T16_17_06_035Z-debug.log
Error: Process completed with exit code 1.

And Im firmly believe that is not my fault in this case, please, don't reject this PR because of that minor thing. At the time I make this comment, I already google it but without any solution that fix this. It could be related with an update made it to stylelint package.

**Comment by Mihndim2020** [comment]
Hello @TheLuisAbarca, to solve the issue, please follow these steps;
- Delete `node_modules` directory in your local repository, 
- Delete `package-lock.json file` in your local repository,
- Run `npm install` in your root directory( this will recreate `node_modules directory and the package-lock.json file`)'
- Commit the changes, resolve conflicts if any, and push to your remote repository. That should solve the issue.

**Comment by TheLuisAbarca** [comment]
> Hello @TheLuisAbarca, to solve the issue, please follow these steps;
> 
>     * Delete `node_modules` directory in your local repository,
> 
>     * Delete `package-lock.json file` in your local repository,
> 
>     * Run `npm install` in your root directory( this will recreate `node_modules directory and the package-lock.json file`)'
> 
>     * Commit the changes, resolve conflicts if any, and push to your remote repository. That should solve the issue.

Ok @Mihndim2020, Thank you, I'm going to give it a try.

**Comment by TheLuisAbarca** [comment]
> > Hello @TheLuisAbarca, to solve the issue, please follow these steps;
> > ```
> > * Delete `node_modules` directory in your local repository,
> > 
> > * Delete `package-lock.json file` in your local repository,
> > 
> > * Run `npm install` in your root directory( this will recreate `node_modules directory and the package-lock.json file`)'
> > 
> > * Commit the changes, resolve conflicts if any, and push to your remote repository. That should solve the issue.
> > ```
> 
> Ok @Mihndim2020, Thank you, I'm going to give it a try.

IT WORKS!, @Mihndim2020 thank you so much! :+1:

**Comment by Mihndim2020** [comment]
> > > Hello @TheLuisAbarca, to solve the issue, please follow these steps;
> > > ```
> > > * Delete `node_modules` directory in your local repository,
> > > 
> > > * Delete `package-lock.json file` in your local repository,
> > > 
> > > * Run `npm install` in your root directory( this will recreate `node_modules directory and the package-lock.json file`)'
> > > 
> > > * Commit the changes, resolve conflicts if any, and push to your remote repository. That should solve the issue.
> > > ```
> > 
> > 
> > Ok @Mihndim2020, Thank you, I'm going to give it a try.
> 
> IT WORKS!, @Mihndim2020 thank you so much! 👍

You are welcome man!

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
### Hi @TheLuisAbarca, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
